# Generated by Django 5.1.5 on 2025-02-11 07:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('willaTestApp', '0003_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7da415d3-e84d-11ef-9458-cc1531b3835e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
