# Generated by Django 5.1.5 on 2025-02-14 08:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('willaTestApp', '0008_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(default=uuid.UUID('315c9511-eab1-11ef-823d-cc1531b3835e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
