# Generated by Django 5.1.5 on 2025-02-14 09:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('willaTestApp', '0011_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5df30864-eab3-11ef-9df2-cc1531b3835e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
